markdown: redcarpet

# disabled until jekyll supports redcarpet 2.1.1 which (hopefully) doesn't do
# smart quotes inside of <code> tags
#redcarpet:
  #extensions: [smart]
pygments: true
permalink: /:title.html
